---
annotations:
  category: "Infrastructure"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/license: "Apache-2.0"
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: nautobot
      image: ghcr.io/nautobot/nautobot:1.2.2
  artifacthub.io/links: |
    - name: Nautobot Documentation
      url: https://nautobot.readthedocs.io/en/stable/
    - name: Nautobot
      url: https://github.com/nautobot/nautobot
  artifacthub.io/screenshots: |
    - title: Main Page
      url: https://raw.githubusercontent.com/nautobot/nautobot/develop/nautobot/docs/media/screenshot1.png
    - title: Rack Elevation
      url: https://raw.githubusercontent.com/nautobot/nautobot/develop/nautobot/docs/media/screenshot2.png
    - title: Prefix hierarchy
      url: https://raw.githubusercontent.com/nautobot/nautobot/develop/nautobot/docs/media/screenshot3.png
  artifacthub.io/changes: |
    - kind: changed
      description: {{{prTitle}}}
    - kind: added
      description: Security Scanning & Remediations for medium/high findings
      links:
        - name: Github Issue
          url: https://github.com/nautobot/helm-charts/issues/87
    - kind: added
      description: PostgreSQL High Availability Support
      links:
        - name: Github Issue
          url: https://github.com/nautobot/helm-charts/issues/35
    - kind: changed
      description: Update ghcr.io/nautobot/nautobot Docker tag to v1.2.1
    - kind: added
      description: Redis Sentinel Documentation
      links:
        - name: Github Issue
          url: https://github.com/nautobot/helm-charts/issues/35
    - kind: added
      description: MySQL Support
      links:
        - name: Github Issue
          url: https://github.com/nautobot/helm-charts/issues/15
    - kind: changed
      description: Updated Redis with TLS documentation
      links:
        - name: Github Issue
          url: https://github.com/nautobot/helm-charts/issues/57
    - kind: changed
      description: Bumping sub-chart dependencies
    - kind: changed
      description: Upgraded Nautobot to 1.2.1
      links:
        - name: Github Issue
          url: https://github.com/nautobot/helm-charts/issues/47
    - kind: added
      description: Added Celery Beat for Nautobot 1.2 support
      links:
        - name: Github Issue
          url: https://github.com/nautobot/helm-charts/issues/47
apiVersion: "v2"
appVersion: "1.2.2"
dependencies:
  - condition: "redis.enabled"
    name: "redis"
    repository: "https://charts.bitnami.com/bitnami"
    version: "15.X.X"
  - condition: "postgresql.enabled"
    name: "postgresql"
    repository: "https://charts.bitnami.com/bitnami"
    version: "10.x.x"
  - condition: "postgresqlha.enabled"
    name: "postgresql-ha"
    repository: "https://charts.bitnami.com/bitnami"
    version: "8.x.x"
    alias: "postgresqlha"
  - condition: "mariadb.enabled"
    name: "mariadb"
    repository: "https://charts.bitnami.com/bitnami"
    version: "10.x.x"
  - name: "common"
    repository: "https://charts.bitnami.com/bitnami"
    tags:
      - "bitnami-common"
    version: "1.x.x"
description: "Nautobot is a Network Source of Truth and Network Automation Platform."
engine: "gotpl"
home: "https://github.com/nautobot/nautobot"
icon: "https://raw.githubusercontent.com/nautobot/helm-charts/main/images/NautobotLogoSquare.png"
keywords:
  - "DCIM"
  - "IPAM"
  - "SOT"
maintainers:
  - email: "opensource@networktocode.com"
    name: "Network to Code"
    url: "https://www.networktocode.com/"
name: "nautobot"
sources:
  - "https://github.com/nautobot/nautobot"
  - "https://github.com/nautobot/helm-charts"
version: "1.1.0"
