---
annotations:
  category: "Infrastructure"
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/license: "Apache-2.0"
  artifacthub.io/prerelease: "false"
  artifacthub.io/images: |
    - name: nautobot
      image: ghcr.io/nautobot/nautobot:1.6.2-py3.11
  artifacthub.io/links: |
    - name: Nautobot Documentation
      url: https://docs.nautobot.com/
    - name: Nautobot Core Documentation
      url: https://nautobot.readthedocs.io/en/stable/
    - name: Nautobot Helm Chart Documentation
      url: https://docs.nautobot.com/projects/helm-charts/en/stable
    - name: Nautobot
      url: https://github.com/nautobot/nautobot
  artifacthub.io/screenshots: |
    - title: Main Page
      url: https://raw.githubusercontent.com/nautobot/nautobot/develop/nautobot/docs/media/ss_main_page.png
    - title: Config Contexts
      url: https://raw.githubusercontent.com/nautobot/nautobot/develop/nautobot/docs/media/ss_config_contexts.png
    - title: GraphQL
      url: https://raw.githubusercontent.com/nautobot/nautobot/develop/nautobot/docs/media/ss_graphiql.png
    - title: Prefix hierarchy
      url: https://raw.githubusercontent.com/nautobot/nautobot/develop/nautobot/docs/media/ss_prefix_hierarchy.png
    - title: Config Compliance
      url: https://raw.githubusercontent.com/nautobot/nautobot/develop/nautobot/docs/media/ss_plugin_golden_config.png
    - title: Chatops
      url: https://raw.githubusercontent.com/nautobot/nautobot/develop/nautobot/docs/media/ss_plugin_chatops.png
  artifacthub.io/changes: |
    - kind: fixed
      description: Fixed #306 Bug: configured prometheus backend not possible
    - kind: fixed
      description: Fixed #316 Concurrency int breaks deployment
    - kind: fixed
      description: Fixed #255 Switch dependencies to OCI
    - kind: changed
      description: Upgraded Nautobot from 1.5.23 to 1.6.2
    - kind: changed
      description:  Upgraded Mariadb subchart from 12.2.5 to 13.1.3
    - kind: changed
      description:  Upgraded PostgreSQL subchart from 12.5.7 to 12.12.4
    - kind: changed
      description:  Upgraded PostgreSQL-HA subchart from 11.7.5 to 11.9.4
    - kind: changed
      description:  Upgraded RabbitMQ subchart from 12.0.1 to 12.1.5
    - kind: changed
      description:  Upgraded Redis subchart from 17.11.5 to 18.0.4
apiVersion: "v2"
appVersion: "1.6.2"
version: "2.0.4"
dependencies:
  - condition: "redis.enabled"
    name: "redis"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "18.x.x"
  - condition: "postgresql.enabled"
    name: "postgresql"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "12.x.x"
  - condition: "postgresqlha.enabled"
    name: "postgresql-ha"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "11.x.x"
    alias: "postgresqlha"
  - condition: "mariadb.enabled"
    name: "mariadb"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "13.x"
  - condition: "rabbitmq.enabled"
    name: "rabbitmq"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    version: "12.x"
  - name: "common"
    repository: "oci://registry-1.docker.io/bitnamicharts"
    tags:
      - "bitnami-common"
    version: "2.x.x"
description: "Nautobot is a Network Source of Truth and Network Automation Platform."
home: "https://github.com/nautobot/nautobot"
icon: "https://raw.githubusercontent.com/nautobot/helm-charts/main/images/NautobotLogoSquare.png"
keywords:
  - "DCIM"
  - "IPAM"
  - "SOT"
maintainers:
  - email: "opensource@networktocode.com"
    name: "Network to Code"
    url: "https://www.networktocode.com/"
name: "nautobot"
sources:
  - "https://github.com/nautobot/nautobot"
  - "https://github.com/nautobot/helm-charts"
