---
rqWorker:
  enabled: true

postgresql:
  postgresqlPassword: "change-me"
redis:
  auth:
    password: "change-me"

ingress:
  enabled: true
  path: "/*"

metrics:
  enabled: true
  capacityMetrics:
    enabled: true
  prometheusRule:
    enabled: true
